# Generated by Django 5.1.4 on 2025-01-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0002_alter_todoitem_title_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
