# Generated by Django 5.1.4 on 2025-01-25 17:39

import chawtsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to=chawtsApp.models.profilePicUniqueUpload),
        ),
    ]
