# Generated by Django 5.1.4 on 2025-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
