# Generated by Django 5.1.4 on 2025-01-26 16:52

import chawtsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0006_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=chawtsApp.models.profilePicUniqueUpload),
        ),
    ]
