# Generated by Django 5.1.4 on 2025-02-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField(default=None)),
            ],
            options={
                'db_table': 'entityChildren',
            },
        ),
        migrations.AlterModelTableComment(
            name='profile',
            table_comment='An extension of the django User model for some extra info',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='entityParents',
        ),
        migrations.CreateModel(
            name='FamilyAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chawtsApp.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chawtsApp.profile')),
            ],
            options={
                'db_table_comment': 'Stores who the parents are of which children',
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='chawtsApp.FamilyAssociation', to='chawtsApp.profile'),
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeEntry', models.DateTimeField(auto_now_add=True)),
                ('timeEvent', models.DateTimeField()),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('calories', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='chawtsApp.child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sleep', 'Sleep'), ('food', 'Food'), ('growth', 'Growth')], max_length=50)),
                ('timeEntry', models.DateTimeField(auto_now_add=True)),
                ('timeEvent', models.DateTimeField()),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('headCircumfrance', models.FloatField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='chawtsApp.child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeEntry', models.DateTimeField(auto_now_add=True)),
                ('timeEvent', models.DateTimeField()),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('sleep', 'Sleep'), ('nap', 'Nap'), ('siesta', 'Siesta')], max_length=50)),
                ('duration', models.DurationField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to='chawtsApp.child')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
