# Generated by Django 5.1.4 on 2025-02-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0008_child_alter_profile_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='child',
            table='chawts_entityChildren',
        ),
        migrations.AlterModelTable(
            name='familyassociation',
            table='chawts_FamilyAssociation',
        ),
        migrations.AlterModelTable(
            name='foodlog',
            table='chawts_logFood',
        ),
        migrations.AlterModelTable(
            name='growthlog',
            table='chawts_logGrowth',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='chawts_entityParents',
        ),
        migrations.AlterModelTable(
            name='sleeplog',
            table='chawts_logSleep',
        ),
    ]
