# Generated by Django 5.1.4 on 2025-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0009_alter_child_table_alter_familyassociation_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='shareCode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
