# Generated by Django 5.1.4 on 2025-02-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0010_child_sharecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='chawtsApp.FamilyAssociation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyassociation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
