# Generated by Django 5.1.6 on 2025-02-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0011_alter_child_parents_alter_familyassociation_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodLogs', to='chawtsApp.child'),
        ),
        migrations.AlterField(
            model_name='growthlog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growthLogs', to='chawtsApp.child'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleepLogs', to='chawtsApp.child'),
        ),
        migrations.AlterModelTable(
            name='child',
            table='chawts_child',
        ),
        migrations.AlterModelTable(
            name='familyassociation',
            table='chawts_families',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='chawts_userExtended',
        ),
    ]
