# Generated by Django 5.1.6 on 2025-02-13 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0012_alter_foodlog_child_alter_growthlog_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='foodlog',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='growthlog',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='growthlog',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='tag',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='growthlog',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='timeEvent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='growthlog',
            name='timeEvent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='timeEvent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
