# Generated by Django 5.1.6 on 2025-02-14 13:35

import chawtsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0013_remove_foodlog_comments_remove_foodlog_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=chawtsApp.models.profilePicUniqueUpload),
        ),
    ]
