# Generated by Django 5.1.6 on 2025-02-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0014_child_profile_picture'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='familyassociation',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='profile',
            table_comment=None,
        ),
    ]
