# Generated by Django 5.1.6 on 2025-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0015_alter_familyassociation_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='amount',
            field=models.DecimalField(choices=[(0.0, 'None'), (0.25, 'Some'), (0.5, 'Half'), (0.75, 'Most'), (1.0, 'Full')], decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='type',
            field=models.CharField(choices=[('formula', 'Formula'), ('cowMilk', 'Cow Milk'), ('breastMilk', 'Breast Milk'), ('pasta', 'Pasta'), ('jacketPotato', 'Jacket potato'), ('chickenCurryWithRice', 'Chicken curry with rice'), ('risotto', 'Risotto'), ('chilliConCarne', 'Chilli con carne')], max_length=50),
        ),
    ]
