# Generated by Django 5.1.6 on 2025-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0016_foodlog_amount_alter_foodlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
