# Generated by Django 5.1.6 on 2025-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0017_alter_foodlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='mealType',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='type',
            field=models.CharField(choices=[('sleep', 'Sleep'), ('food', 'Food'), ('growth', 'Growth')], max_length=50),
        ),
    ]
