# Generated by Django 5.1.6 on 2025-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0018_foodlog_mealtype_alter_foodlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='mealType',
            field=models.CharField(choices=[('formula', 'Formula'), ('cowMilk', 'Cow Milk'), ('breastMilk', 'Breast Milk')], max_length=50),
        ),
    ]
