# Generated by Django 5.1.6 on 2025-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0019_alter_foodlog_mealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='mealType',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
