# Generated by Django 5.1.6 on 2025-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chawtsApp', '0020_alter_foodlog_mealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='mealType',
            field=models.CharField(choices=[('pasta', 'Pasta'), ('jacketPotato', 'Jacket potato'), ('chickenCurryWithRice', 'Chicken curry with rice'), ('risotto', 'Risotto'), ('chilliConCarne', 'Chilli con carne')], max_length=50),
        ),
    ]
